[[language]]
name = "helm"
scope = "source.helm"
injection-regex = "^helm$"
file-types = ["helm.yaml", "templates/*.yaml", { suffix = "templates/*.yaml" }, { suffix = "helm.yaml" }]
roots = ["Chart.yaml"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "helm_ls", args = ["serve"] }
grammar = "helm"

[[grammar]]
name = "helm"
source = { git = "https://github.com/dannylongeuay/tree-sitter-go-template", rev = "395a33e08e69f4155156f0b90138a6c86764c979" }

# Added to source 3/4/23: https://github.com/helix-editor/helix/pull/6159
# [[language]]
# name = "graphql"
# scope = "source.graphql"
# injection-regex = "graphql"
# file-types = ["gql", "graphql", "graphqls"]
# roots = []
# comment-token = "#"
# indent = { tab-width = 2, unit = "  " }
# language-server = { command = "graphql-lsp", args = ["server", "-m", "stream"] }
# grammar = "graphql"

# [[grammar]]
# name = "graphql"
# source = { git = "https://github.com/bkegley/tree-sitter-graphql", rev = "5e66e961eee421786bdda8495ed1db045e06b5fe" }
